name: Build APK

on:
 workflow_dispatch:
    inputs:
      build_type:
        description: 'release'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - debug
     

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
          
    - name: Set executable permission for gradlew
      run: chmod +x gradlew    

    - name: Checkout Keystore Repository
      uses: actions/checkout@v4
      with:
        repository: tvgood/keystore-repo  
        token: ${{ secrets.TOKEN }}
        path: keystore

    - name: Verify secrets
      run: |
        echo "KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}"
        echo "KEY_ALIAS: ${{ secrets.KEY_ALIAS }}"
        echo "KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}"
        if [ -z "${{ secrets.KEYSTORE_PASSWORD }}" ] || [ -z "${{ secrets.KEY_ALIAS }}" ] || [ -z "${{ secrets.KEY_PASSWORD }}" ]; then
          echo "ERROR: One or more secrets are empty!"
          exit 1
        fi

   
    - name: Build with Gradle (using -P)
      run: |
        ./gradlew clean assemble${{ inputs.build_type }} \
          -PstorePassword=${{ secrets.KEYSTORE_PASSWORD }} \
          -PkeyAlias=${{ secrets.KEY_ALIAS }} \
          -PkeyPassword=${{ secrets.KEY_PASSWORD }}

    - name: Verify APK signature
      run: |
        jarsigner -verify -verbose -certs app/build/outputs/apk/release/*.apk

    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/*.apk
